/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kayipcheung' at '2/17/17 10:24 AM' with Gradle 3.2.1
 *
 * @author kayipcheung, @date 2/17/17 10:24 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
